server:
 port: 2022
spring:
 datasource:
  url: jdbc:postgresql://${PullPoint_DBHost}:${PullPoint_DBPort}/${PullPoint_DBName}
  #url: "jdbc:postgresql://localhost:5432/pull-point"
  username: ${PullPoint_DBUser}
  password: ${PullPoint_DBPassword}
 jpa:
  hibernate.ddl-auto: create-drop
  generate-ddl: true
  show-sql: true
  properties:
    hibernate:
     dialect: org.hibernate.dialect.PostgreSQLDialect
 mail:
  host: smtp.gmail.com
  username: pullpointdev@gmail.com
  password: vxezqmlogbbpicae
 jackson:
  deserialization:
   use_java_array_for_json_array: true
springdoc:
  swagger-ui:
   path: /api
pullpoint:
  jwtSecret: pUlLp0iNt212aRt1sTaPp1iCatIon1
